WebApp/Models/HomeViewModel.cs
using Fr.EQL.AI110.DLD_GB.Entities;

namespace Fr.EQL.AI110.DLD_GB.Web.Models;

public class HomeViewModel
{


    public List<Partner> Partners { get; set; }
    public List<Adherent> Adherents { get; set; }

    public int IdAdherent { get; set; }
    public int IdPartner { get; set; }

    public HomeViewModel()
    {
    }

}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;
using Fr.EQL.AI110.DLD_GB.Business;
using Fr.EQL.AI110.DLD_GB.Entities;
using Fr.EQL.AI110.DLD_GB.Web.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            PartnerBusiness partnerBusiness = new PartnerBusiness();
            AdherentBusiness adherentBusiness = new AdherentBusiness(); 
            HomeViewModel homeViewModel = new HomeViewModel();


            homeViewModel.Partners = partnerBusiness.GetAllPartner();
            homeViewModel.Adherents = adherentBusiness.GetAllAdherents();

            return View(homeViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/PartnerController.cs
using Microsoft.AspNetCore.Mvc;
using Fr.EQL.AI110.DLD_GB.Business;
using Fr.EQL.AI110.DLD_GB.Entities;
using Fr.EQL.AI110.DLD_GB.Web.Models;

namespace Fr.EQL.AI110.DLD_GB.Web.Controllers
{
    public class PartnerController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {   
            PartnerSearchViewModel model = new PartnerSearchViewModel();

            PartnerBusiness PartnerBusiness = new PartnerBusiness();
            model.Partners = PartnerBusiness.GetAllPartner();

            VilleCPBusiness villeCPBusiness = new VilleCPBusiness();
            model.VilleCPs = villeCPBusiness.GetAllVilleCP(); 

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(PartnerSearchViewModel model)
		{
            PartnerBusiness partnerBusiness = new PartnerBusiness();
            model.Partners = partnerBusiness.SearchPartner(model.Name, model.Siret, model.VilleId);

            VilleCPBusiness villeCPBusiness = new VilleCPBusiness();
            model.VilleCPs = villeCPBusiness.GetAllVilleCP();
            return View(model);
		}

        [HttpGet]
        public IActionResult DonationToStock(int IdPartner)
        {
            PartnerBusiness DonationBusiness = new PartnerBusiness();
            DonationBusiness donationBusiness = new DonationBusiness();

            DonationSearchViewModel model = new DonationSearchViewModel();

            model.DonationsDetails = donationBusiness.GetDonationByIdPartner(IdPartner);
            model.IdPartner = IdPartner;
            ViewBag.IdPartner = IdPartner;

            return View(model);

        }

    }
}

WebApp/Controllers/StorageAreaController.cs
using Fr.EQL.AI110.DLD_GB.Business;
using Fr.EQL.AI110.DLD_GB.Entities;
using Fr.EQL.AI110.DLD_GB.Web.Models;
using Microsoft.AspNetCore.Mvc;


namespace Fr.EQL.AI110.DLD_GB.Web.Controllers
{
	public class StorageAreaController : Controller
	{
		[HttpGet]
		public IActionResult Update(int id)
		{
            StorageViewModel model = new StorageViewModel();

            TailleBusiness tailleBusiness = new TailleBusiness();
            VilleCPBusiness villeCPBusiness = new VilleCPBusiness();
            TemperatureStockageBusiness temperatureStockageBusiness = new TemperatureStockageBusiness();
            PartnerBusiness partenaireBusiness = new PartnerBusiness();
            StorageAreaBusiness storageAreaBu = new StorageAreaBusiness();

            model.Villes = villeCPBusiness.GetAllVilleCP();
            model.Tailles = tailleBusiness.GetAllTaille();
            model.Temperatures = temperatureStockageBusiness.GetAllTemperatureStockage();
            model.Partenaires = partenaireBusiness.GetAllPartner();         
            model.StorageArea = storageAreaBu.GetStorageAreaById(id);

			return View ("create", model);
		}

		[HttpPost]
		public IActionResult Update(StorageArea storageArea, int id)
		{
		    StorageAreaBusiness storageAreaBu = new StorageAreaBusiness();
            storageArea.Id = id;
		    storageAreaBu.UpdateStorageArea(storageArea);
            return RedirectToAction("Index", new { IdPartner = storageArea.PartenaireId});
		}

        [HttpGet]
        public IActionResult Create(int IdPartner)
        {
            StorageViewModel model = new StorageViewModel();

            PartnerBusiness partnerBusiness = new PartnerBusiness();
            TailleBusiness tailleBusiness = new TailleBusiness();
            VilleCPBusiness villeCPBusiness = new VilleCPBusiness();
            TemperatureStockageBusiness temperatureStockageBusiness = new TemperatureStockageBusiness();
            PartnerBusiness partenaireBusiness = new PartnerBusiness();

            // Alimenter le viewModel
            model.Villes = villeCPBusiness.GetAllVilleCP();
            model.Tailles = tailleBusiness.GetAllTaille();
            model.Temperatures = temperatureStockageBusiness.GetAllTemperatureStockage();
            model.Partenaires = partenaireBusiness.GetAllPartner();
            model.IdPartner = IdPartner;
            ViewBag.IdPartner = IdPartner;
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(StorageViewModel model)
        {
            StorageAreaBusiness storageAreaBusiness = new StorageAreaBusiness();
            PlageHoraireBusiness plageHoraireBusiness = new PlageHoraireBusiness();
            //List<PlageHoraire> plages = new List<PlageHoraire>();
            //plages.Add(model.PlageHoraireLundi);
            //plages.Add(model.PlageHoraireMardi);
            //plages.Add(model.PlageHoraireMercredi);
            //plages.Add(model.PlageHoraireJeudi);
            //plages.Add(model.PlageHoraireVendredi);
            //plages.Add(model.PlageHoraireSamedi);
            //plages.Add(model.PlageHoraireDimanche);

            storageAreaBusiness.SaveStorageArea(model.StorageArea);

            //foreach(PlageHoraire p in plages)
            //{
            //    plageHoraireBusiness.SavePlageHoraire(p, model.StorageArea);
            //}
            

            return RedirectToAction("Create");
        }

        public IActionResult Cancel(int id, int IdPartner)
        {
            StorageAreaBusiness storageAreaBusiness = new StorageAreaBusiness();
            storageAreaBusiness.CancelStorageArea(id);
            ViewBag.IdPartner = IdPartner;
            return RedirectToAction("Index", new {IdPartner});
        }

        public IActionResult Index(int IdPartner)
        {
            StorageViewModel model = new StorageViewModel();
            StorageAreaBusiness storageAreaBusiness = new StorageAreaBusiness();
            PlageHoraireBusiness plageHoraireBusiness = new PlageHoraireBusiness();

            ViewBag.IdPartner = IdPartner;
            model.StorageAreasDetails = storageAreaBusiness.GetStorageAreasByIdPartner(IdPartner);
           
            model.IdPartner = IdPartner;

            return View(model);
        }
    }
}

WebApp/Views/Home/Index.cshtml
@using Fr.EQL.AI110.DLD_GB.Entities
@using Fr.EQL.AI110.DLD_GB.Web.Controllers
@using Fr.EQL.AI110.DLD_GB.Web.Models

@model HomeViewModel


<h3>Bienvenue chez <strong>DLD</strong></h3>
<h2>Date Limite de Don, en première ligne contre le gaspillage alimentaire</h2>



Se connecter en tant que ...
<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col" style="width:35rem;">
        <div class="card text-white bg-success mb-3" style="max-width: 50rem;">

            <img src="/image/Partenaire.jpg" class="card-img-top" alt="..." style=" width: 100%;  height: 20vw;object-fit: cover;">

            <div class="card-body">
                <h5 class="card-title">Partenaire</h5>
                <p class="card-text">Hebergez et distribuez les dons des utilisateurs près de chez vous et participez à la lutte contre le gaspillage !</p>
                <label class="visually-hidden" for="inlineFormSelectPref">Preference</label>
               
                <form><select  asp-for="IdPartner" class="form-select" id="inlineFormSelectPref">
                    <option selected>Selectionez un partenaire</option>
                    @foreach (Partner partner in Model.Partners)
                    {
                        <option value="@partner.Id">@partner.NomSociete</option>
                    }
                </select>
                <div class="navbar-wrapper">
                    <div class="container full-width" style="padding:1rem;">
                                    <input type="submit" asp-controller="StorageArea" asp-action="Index"  class="btn btn-primary" value="Ses moyens de stockage"></input>
                       <input type="submit" asp-controller="Partner" asp-action="DonationToStock"  class="btn btn-primary" value="Les dons hébergés"></input>
                    </div>
                    </form>
                </div>
            </div>
            <div class="card-footer text-muted">
                <a href="#" class="link-light">Créer un compte Partenaire</a>
            </div>
        </div>
    </div>

    <div class="col" style="width:35rem;">
        <div class="card text-dark bg-warning mb-3" style="max-width: 50rem;">

            <img src="/image/Adherent.jpg" class="card-img-top" alt="..." style=" width: 100%;  height: 20vw;object-fit: cover;">

            <div class="card-body">
                <h5 class="card-title">Adherent</h5>
                <p class="card-text">Rejoignez nous dans la lutte contre le gaspillage ! Donnez vos produits alimentaire en surplus et bénéficiez de dons des autres adhérents</p>
                <label class="visually-hidden" for="inlineFormSelectPref">Preference</label>
                <form>
                    <select asp-for="IdAdherent" class="form-select" id="inlineFormSelectPref">
                        <option selected>Selectionez un adhérent</option>
                        @foreach (Adherent adherent in Model.Adherents)
                        {
                            <option value="@adherent.Id">@adherent.NomUtilisateur</option>
                        }
                    </select>

                    <div class="navbar-wrapper">
                        <div class="container full-width" style="padding:1rem;">
                            <input type="submit" asp-controller="donation" asp-action="Index"  class="btn btn-primary" value="Reserver un don"></input>
                            <input type="submit" asp-controller="donation" asp-action="Proposed"  class="btn btn-primary" value="Gérer ses dons"></input>
                            <input type="submit" asp-controller="donation" asp-action="Create1"  class="btn btn-primary" value="Déposer un don"></input>
                        </div>
                    </div>
                </form>
                <div>


                    <div class="card-footer text-muted">
                        <a href="#" class="link-dark">Créer un compte Adhérent</a>
                    </div>
                </div>
            </div>
        </div>

    </div>