WebApp/Controllers/CagnotteViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Fr.EQL.AI110.DLD_GB.Business;
using Fr.EQL.AI110.DLD_GB.Entities;
using Fr.EQL.AI110.DLD_GB.Web.Models;

namespace Fr.EQL.AI110.ChristmasFactory.Web.Controllers
{
    public class CagnotteViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke(int IdAdherent)
        {
            TransactionBusiness transactionBusiness = new TransactionBusiness();
            int Cagnotte = transactionBusiness.CagnotteByAdherentId(IdAdherent);
         
            return View(Cagnotte);
        }
    }
}

WebApp/Controllers/DonationController.cs
using Fr.EQL.AI110.DLD_GB.Business;
using Fr.EQL.AI110.DLD_GB.Entities;
using Fr.EQL.AI110.DLD_GB.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;





namespace Fr.EQL.AI110.DLD_GB.Web.Controllers
{


    public class DonationController : Controller
    {
        public static int RayonIdStatic = 0;
        public static int CategorieIdStatic = 0;
        public static int ProduitIdStatic = 0;
        public static int IdAdherentStatic = 0;


        [HttpGet]
        public IActionResult Index(int IdAdherent)
        {
            
            AdherentBusiness adherentBusiness = new AdherentBusiness();
            DonationBusiness DonationBusiness = new DonationBusiness();
            CategorieBusiness CategorieBusiness = new CategorieBusiness();
            TailleBusiness tailleBusiness = new TailleBusiness();
            RayonBusiness rayonBusiness = new RayonBusiness();
            TemperatureStockageBusiness temperatureStockageBusiness = new TemperatureStockageBusiness();
            UniteMesureBusiness uniteMesureBusiness = new UniteMesureBusiness();
            VilleCPBusiness villeCPBusiness = new VilleCPBusiness();
            ProduitBusiness produitBusiness = new ProduitBusiness();
            ViewBag.IdAdherent = IdAdherent;
            IdAdherentStatic = IdAdherent;

            DonationSearchViewModel model = new DonationSearchViewModel();

            model.Produits = produitBusiness.GetAllProduit();
            model.DonationsDetails = DonationBusiness.GetDonationByMultiCriteria(0, 0, 0, "", "", "", "", 0, "", "", "", null, true, null, null, null, null);
            model.Categories = CategorieBusiness.GetAllCategorie();
            model.Tailles = tailleBusiness.GetAllTaille();
            model.Rayons = rayonBusiness.GetAllRayon();
            model.TemperaturesStockage = temperatureStockageBusiness.GetAllTemperatureStockage();
            model.UnitesMesure = uniteMesureBusiness.GetAllUniteMesure();
            model.Villes = villeCPBusiness.GetAllVilleCP();
            model.Adherent = adherentBusiness.GetAdherentById(IdAdherent);

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(DonationSearchViewModel model)
        {
            bool? box = null;

            if (model.IdToReserve > 0) 

            if (model.RayonId != 0)
            {
                RayonIdStatic = model.RayonId;
                CategorieIdStatic = 0;
                ProduitIdStatic = 0;
            }
            else if (RayonIdStatic != 0 && model.CategorieId == 0 && model.RayonId == 0 && model.ProduitId == 0 && CategorieIdStatic == 0) model.RayonId = RayonIdStatic;

            if (model.CategorieId != 0)
            {
                CategorieIdStatic = model.CategorieId;
                ProduitIdStatic = 0;
            }
            else if (CategorieIdStatic != 0 && model.CategorieId == 0 && model.RayonId == 0 && model.ProduitId == 0 && ProduitIdStatic == 0) model.CategorieId = CategorieIdStatic;

            if (model.ProduitId != 0) ProduitIdStatic = model.ProduitId;
            else if (ProduitIdStatic != 0 && model.CategorieId == 0 && model.RayonId == 0 && model.ProduitId == 0) model.ProduitId = ProduitIdStatic;


            if (model.reset == true)
            {
                model.CategorieId = 0;
                model.RayonId = 0;
                model.ProduitId = 0;
                RayonIdStatic = 0;
                CategorieIdStatic = 0;
                ProduitIdStatic = 0;
    }

            AdherentBusiness adherentBusiness = new AdherentBusiness();
            DonationBusiness DonationBusiness = new DonationBusiness();
            VilleCPBusiness VilleCPBusiness = new VilleCPBusiness();
            CategorieBusiness CategorieBusiness = new CategorieBusiness();
            TailleBusiness tailleBusiness = new TailleBusiness();
            RayonBusiness rayonBusiness = new RayonBusiness();
            TemperatureStockageBusiness temperatureStockageBusiness = new TemperatureStockageBusiness();
            UniteMesureBusiness uniteMesureBusiness = new UniteMesureBusiness();
            VilleCPBusiness villeCPBusiness = new VilleCPBusiness();
            ProduitBusiness produitBusiness = new ProduitBusiness();



                if (!string.IsNullOrEmpty(model.Ville)) model.ListeVillesProches = VilleCPBusiness.listeVillesProches(VilleCPBusiness.GetVilleCPByNomDeVille(model.Ville), model.Distance);
            if (model.Box == true) box = true;

            model.DonationsDetails = DonationBusiness.GetDonationByMultiCriteria(model.RayonId, model.CategorieId, model.ProduitId, model.NomRayon, model.NomCategorie, model.NomProduit,
                                     model.UniteMesure, model.QuantiteProduit, model.TemperatureStockage, model.Ville, model.TypeStockage,
                                     box, true, model.ListeVillesProches, model.ListeCategories, model.ListeRayons, model.ListeProduits);


            if (model.RayonId == 0 && model.CategorieId == 0 && model.ProduitId == 0)
            {
                model.Categories = CategorieBusiness.GetAllCategorie();
                model.Produits = produitBusiness.GetAllProduit();
            }

            else if (model.RayonId != 0 && model.CategorieId == 0 && model.ProduitId == 0)
            {
                model.Categories = CategorieBusiness.GetCategorieByRayonId(model.RayonId);
                model.RayonActuel = rayonBusiness.GetRayonById(model.RayonId);
            }

            else if (model.RayonId == 0 && model.CategorieId != 0 && model.ProduitId == 0)
            {
                model.Produits = produitBusiness.GetProduitByIdCategorieId(model.CategorieId);
                model.RayonActuel = CategorieBusiness.GetRayonParentByIdCategorie(model.CategorieId);
                model.CategorieActuelle = CategorieBusiness.GetCategorieById(model.CategorieId);
            }

            else if (model.RayonId == 0 && model.CategorieId == 0 && model.ProduitId != 0)
            {
                model.RayonActuel = CategorieBusiness.GetRayonParentByIdCategorie(produitBusiness.GetCategorieParentByIdProduit(model.ProduitId).Id);
                model.CategorieActuelle = produitBusiness.GetCategorieParentByIdProduit(model.ProduitId);
                model.ProduitActuel = produitBusiness.GetProduitById(model.ProduitId);
                model.NomProduit = produitBusiness.GetProduitById(model.ProduitId).Nom;
            }

            model.Tailles = tailleBusiness.GetAllTaille();
            model.Rayons = rayonBusiness.GetAllRayon();
            model.TemperaturesStockage = temperatureStockageBusiness.GetAllTemperatureStockage();
            model.UnitesMesure = uniteMesureBusiness.GetAllUniteMesure();
            model.Villes = villeCPBusiness.GetAllVilleCP();
            model.Adherent = adherentBusiness.GetAdherentById(IdAdherentStatic);

            return View(model);
        }

        public IActionResult ReserverUnDon(int IdToReserve, int idAdherent)
        {
            DonationBusiness donationBusiness = new DonationBusiness();
            donationBusiness.ReserveDonation(IdToReserve, idAdherent);
            return RedirectToAction("Index", new {idAdherent });
        }

        public IActionResult ConfirmerRecuperationDeDon(int IdToConfirm, int idAdherent)
        {
            DonationBusiness donationBusiness = new DonationBusiness();
            donationBusiness.ConfirmerReceptionDeDon(IdToConfirm);

            return RedirectToAction("Proposed", new {idAdherent});
        }

        public IActionResult ConfirmerDepot(int IdDon, int idAdherent)
        {
            DonationBusiness donationBusiness = new DonationBusiness();
            donationBusiness.ConfirmerDepotDon(IdDon);
            return RedirectToAction("Proposed", new { idAdherent = idAdherent });
        }

        public IActionResult CancelReservation(int IdDon, int idAdherent)
        {
            DonationBusiness donationBusiness = new DonationBusiness();
            donationBusiness.CancelReservation(IdDon);
            return RedirectToAction("Proposed", new { idAdherent = idAdherent });
        }

        private IActionResult EditerDon(string rubrique, Donation donation)
        {
            ViewBag.Rubrique = rubrique;
            return View("Create", donation);
        }


        [HttpGet]
        public IActionResult Create1(int IdAdherent)
        {
            AdherentBusiness adherentBu = new AdherentBusiness();
            ViewBag.IdAdherent = IdAdherent;
            RayonBusiness rayonBu = new RayonBusiness();
            CreateDonationViewModel model = new CreateDonationViewModel();
            model.AdherentId = IdAdherent;
            model.AdherentNom = adherentBu.GetAdherentByAdherentId(IdAdherent).Nom;
            model.Rayons = rayonBu.GetAllRayon();

            return View(model);
        }

        [HttpPost]
        public IActionResult Create2(CreateDonationViewModel model)
        {
            AdherentBusiness adherentBu = new AdherentBusiness();
            RayonBusiness rayonBu = new RayonBusiness();
            CategorieBusiness categorieBu = new CategorieBusiness();

            model.AdherentNom = adherentBu.GetAdherentByAdherentId(model.AdherentId).Nom;
            model.Categories = categorieBu.GetAllCategorieByIdRayon(model.RayonId);
            model.RayonNom = rayonBu.GetRayonByIdRayon(model.RayonId).Nom;
            ViewBag.IdAdherent = model.Adherent;
            return View(model);
        }

        [HttpPost]
        public IActionResult Create3(CreateDonationViewModel model)
        {
            AdherentBusiness adherentBu = new AdherentBusiness();
            RayonBusiness rayonBu = new RayonBusiness();
            CategorieBusiness categorieBu = new CategorieBusiness();
            ProduitBusiness produitBu = new ProduitBusiness();

            model.AdherentNom = adherentBu.GetAdherentByAdherentId(model.AdherentId).Nom;

WebApp/Controllers/PanierViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Fr.EQL.AI110.DLD_GB.Business;
using Fr.EQL.AI110.DLD_GB.Entities;
using Fr.EQL.AI110.DLD_GB.Web.Models;

namespace Fr.EQL.AI110.ChristmasFactory.Web.Controllers
{
    public class PanierViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke(int IdAdherent)
        {
           CartBusiness cartBusiness = new CartBusiness();
           
            AddCartViewModel cartViewModel = new AddCartViewModel();
            cartViewModel.CartsDetails = cartBusiness.GetAllCartDetailsByIdAdherent(IdAdherent);
            cartViewModel.TotalArticleAuPanier = cartBusiness.TotalPanierByIdAdherent(IdAdherent);
            cartViewModel.IdAdherent = IdAdherent;
            return View(cartViewModel);
        }
    }
}

WebApp/Controllers/StorageAreaController.cs
using Fr.EQL.AI110.DLD_GB.Business;
using Fr.EQL.AI110.DLD_GB.Entities;
using Fr.EQL.AI110.DLD_GB.Web.Models;
using Microsoft.AspNetCore.Mvc;


namespace Fr.EQL.AI110.DLD_GB.Web.Controllers
{
	public class StorageAreaController : Controller
	{
		[HttpGet]
		public IActionResult Update(int id)
		{
            StorageViewModel model = new StorageViewModel();

            TailleBusiness tailleBusiness = new TailleBusiness();
            VilleCPBusiness villeCPBusiness = new VilleCPBusiness();
            TemperatureStockageBusiness temperatureStockageBusiness = new TemperatureStockageBusiness();
            PartnerBusiness partenaireBusiness = new PartnerBusiness();
            StorageAreaBusiness storageAreaBu = new StorageAreaBusiness();

            model.Villes = villeCPBusiness.GetAllVilleCP();
            model.Tailles = tailleBusiness.GetAllTaille();
            model.Temperatures = temperatureStockageBusiness.GetAllTemperatureStockage();
            model.Partenaires = partenaireBusiness.GetAllPartner();         
            model.StorageArea = storageAreaBu.GetStorageAreaById(id);

			return View ("create", model);
		}

		[HttpPost]
		public IActionResult Update(StorageArea storageArea, int id)
		{
		    StorageAreaBusiness storageAreaBu = new StorageAreaBusiness();
            storageArea.Id = id;
		    storageAreaBu.UpdateStorageArea(storageArea);
            return RedirectToAction("Index", new { IdPartner = storageArea.PartenaireId});
		}

        [HttpGet]
        public IActionResult Create(int IdPartner)
        {
            StorageViewModel model = new StorageViewModel();

            PartnerBusiness partnerBusiness = new PartnerBusiness();
            TailleBusiness tailleBusiness = new TailleBusiness();
            VilleCPBusiness villeCPBusiness = new VilleCPBusiness();
            TemperatureStockageBusiness temperatureStockageBusiness = new TemperatureStockageBusiness();
            PartnerBusiness partenaireBusiness = new PartnerBusiness();

            // Alimenter le viewModel
            model.Villes = villeCPBusiness.GetAllVilleCP();
            model.Tailles = tailleBusiness.GetAllTaille();
            model.Temperatures = temperatureStockageBusiness.GetAllTemperatureStockage();
            model.Partenaires = partenaireBusiness.GetAllPartner();
            model.IdPartner = IdPartner;
            ViewBag.IdPartner = IdPartner;
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(StorageViewModel model)
        {
            StorageAreaBusiness storageAreaBusiness = new StorageAreaBusiness();
            PlageHoraireBusiness plageHoraireBusiness = new PlageHoraireBusiness();
            //List<PlageHoraire> plages = new List<PlageHoraire>();
            //plages.Add(model.PlageHoraireLundi);
            //plages.Add(model.PlageHoraireMardi);
            //plages.Add(model.PlageHoraireMercredi);
            //plages.Add(model.PlageHoraireJeudi);
            //plages.Add(model.PlageHoraireVendredi);
            //plages.Add(model.PlageHoraireSamedi);
            //plages.Add(model.PlageHoraireDimanche);

            storageAreaBusiness.SaveStorageArea(model.StorageArea);

            //foreach(PlageHoraire p in plages)
            //{
            //    plageHoraireBusiness.SavePlageHoraire(p, model.StorageArea);
            //}
            

            return RedirectToAction("Create");
        }

        public IActionResult Cancel(int id, int IdPartner)
        {
            StorageAreaBusiness storageAreaBusiness = new StorageAreaBusiness();
            storageAreaBusiness.CancelStorageArea(id);
            ViewBag.IdPartner = IdPartner;
            return RedirectToAction("Index", new {IdPartner});
        }

        public IActionResult Index(int IdPartner)
        {
            StorageViewModel model = new StorageViewModel();
            StorageAreaBusiness storageAreaBusiness = new StorageAreaBusiness();
            PlageHoraireBusiness plageHoraireBusiness = new PlageHoraireBusiness();

            ViewBag.IdPartner = IdPartner;
            model.StorageAreasDetails = storageAreaBusiness.GetStorageAreasByIdPartner(IdPartner);
           
            model.IdPartner = IdPartner;

            return View(model);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DLD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                          @if (ViewBag.IdAdherent != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Donation" asp-route-idAdherent="@ViewBag.IdAdherent" asp-action="Index">Voir les dons</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="donation" asp-route-idAdherent="@ViewBag.IdAdherent" asp-action="Create1">Proposer un don</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="donation" asp-route-idAdherent="@ViewBag.IdAdherent" asp-action="Proposed">Gerer ses dons</a>
                            </li>
                        }
                       @if (ViewBag.IdPartner != null)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StorageArea" asp-route-IdPartner="@ViewBag.IdPartner" asp-action="Create">Créer un espace de stockage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StorageArea"  asp-route-IdPartner="@ViewBag.IdPartner" asp-action="Index">Liste des espaces de stockage</a>
                        </li>
                         }

                    </ul>

                    @if (ViewBag.IdAdherent != null)
                    {
                        @await Component.InvokeAsync("Panier",new {IdAdherent=ViewBag.IdAdherent})
                        <span class="form-inline my-2 my-lg-0" style="margin:1rem"></span> @await Component.InvokeAsync("Cagnotte",new {IdAdherent=ViewBag.IdAdherent})


                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2021 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>